# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20160209_0828'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorysession',
            name='coursegroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.CourseGroup'),
            preserve_default=False,
        ),
    ]
