# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_delete_coursegroup'),
        ('monitor', '0002_performance_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='activity',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='courses.Activity'),
            preserve_default=False,
        ),
    ]
