# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicalsession',
            name='course_group',
        ),
    ]
