# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20151227_1446'),
        ('schedule', '0002_remove_practicalsession_course_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsession',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labsession',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='labsession',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='practicalsession',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicalsession',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='practicalsession',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='theorysession',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorysession',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='theorysession',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
