# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20151227_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.LabSession')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.PracticalSession')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.TheorySession')),
            ],
        ),
    ]
