# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_labattendance_practicalattendance_theoryattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labattendance',
            name='practical',
        ),
        migrations.RemoveField(
            model_name='practicalattendance',
            name='practical',
        ),
        migrations.RemoveField(
            model_name='theoryattendance',
            name='theory',
        ),
        migrations.DeleteModel(
            name='LabAttendance',
        ),
        migrations.DeleteModel(
            name='PracticalAttendance',
        ),
        migrations.DeleteModel(
            name='TheoryAttendance',
        ),
    ]
