# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20151227_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsession',
            name='name',
            field=models.CharField(default='s', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicalsession',
            name='name',
            field=models.CharField(default='s', max_length=120),
            preserve_default=False,
        ),
    ]
