# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20151228_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='course',
        ),
    ]
