# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_activity_activity_type'),
        ('schedule', '0009_remove_coursegroup_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='course',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
            preserve_default=False,
        ),
    ]
