# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
