# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
