# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20151227_1624'),
        ('schedule', '0007_auto_20151227_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseGroup',
        ),
    ]
