# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_delete_coursegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('duration', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.AddField(
            model_name='topic',
            name='course_module',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='courses.CourseModule'),
            preserve_default=False,
        ),
    ]
