# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20151228_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('de', 'Demostration'), ('pr', 'Presentation'), ('ex', 'Exercise'), ('as', 'Assignment'), ('pr', 'Project'), ('db', 'Debate'), ('qu', 'Questining')], default='1', max_length=15),
            preserve_default=False,
        ),
    ]
