# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 14:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_auto_20160209_0828'),
        ('schedule', '0002_theorysession_coursegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('practical', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.LabSession')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Activity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticalAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('practical', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.PracticalSession')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('theory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.TheorySession')),
            ],
        ),
    ]
